name: E2E Tests

on: [push, pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      # Error: https://github.com/makinzm/cliplex/actions/runs/12446276709/job/34748502856
      - name: Run E2E tests with xvfb
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" 

